version: '2'

services:
  serveo:
    image: taichunmin/serveo:latest
    tty: true
    stdin_open: true
    # Docker for Windows / macOS
    command: >
      autossh -M 0
      -o ServerAliveInterval=60
      -o ServerAliveCountMax=3
      -o ExitOnForwardFailure=yes
      -o StrictHostKeyChecking=no
      -R 80:host.docker.internal:3000
      serveo.net
    # Docker for Linux
    # command: >
    #   HOST_DOMAIN=`ip route|awk '/default/ { print $3 }'`
    #   autossh -M 0
    #   -o ServerAliveInterval=60
    #   -o ServerAliveCountMax=3
    #   -o ExitOnForwardFailure=yes
    #   -o StrictHostKeyChecking=no
    #   -R 80:$HOST_DOMAIN:3000
    #   serveo.net